#pragma once

typedef enum color {
	COLOR_BLACK,
	COLOR_BLUE,
	COLOR_GREEN,
	COLOR_CYAN,
	COLOR_RED,
	COLOR_MAGENTA,
	COLOR_BROWN,
	COLOR_LIGHTGRAY,
	COLOR_DARKGRAY,
	COLOR_LIGHTBLUE,
	COLOR_LIGHTGREEN,
	COLOR_LIGHTCYAN,
	COLOR_LIGHTRED,
	COLOR_LIGHTMAGENTA,
	COLOR_YELLOW,
	COLOR_WHITE,
};

#define COLOR_BORDER COLOR_LIGHTGRAY
#define COLOR_TITLE COLOR_YELLOW
#define COLOR_MENU COLOR_WHITE
#define COLOR_DECOR COLOR_LIGHTBLUE
#define COLOR_SLOGAN COLOR_YELLOW
#define COLOR_DEFAULT COLOR_DARKGRAY
#define COLOR_DEFAULT_TEXT COLOR_WHITE

void gotoxy(int x, int y);
void hide_cursor(void);
void set_color(int color);
void force_disable_ime(void);
void force_english_input(void);